export const experiences = [
  {
    title: "Minha História:",
    text: [
      "Minha paixão por tecnologia começou cedo e me levou a explorar o desenvolvimento web, iniciando com JavaScript. Como desenvolvedor fullstack, busco constantemente soluções eficientes e elegantes, unindo criatividade e resolução de problemas.",
    ],
  },
  {
    title: "Experiência Profissional:",
    text: [
      "**Analista Desenvolvedor FullStack - SysMap Solutions (12/2023 - Atualmente)**",
      "- Atuando como analista desenvolvedor fullstack, com foco no backend",
      "- Frontend: React e Styled Components",
      "- Backend: Node.js, Express, Fastify, Zod, TypeORM, Java",
      "- Testes: Jest e Mockito",
      "- Cloud: AWS Lambda, API Gateway, S3",
      "- Bancos de Dados: ScyllaDB, OracleDB, PostgreSQL, MySQL",
      "",
      "**Primeira Equipe (03/2022 - 06/2022):**",
      "- Analista desenvolvedor fullstack em time de autenticação",
      "- Frontend: React e Styled Components",
      "- Backend: Node.js, Express, Prisma ORM",
      "- Testes: Jest, Mocha e Chai",
      "- Cloud: AWS Lambda, Cognito, API Gateway, S3",
      "- Containers: Docker",
      "",
      "**Full Stack Developer - Uni System Automação e Tecnologia (11/2021 – 02/2022)**",
      "- Desenvolvimento de site web para parque aquático",
      "- Frontend: SASS e Next.JS (responsivo)",
      "- Backend: Nest.JS",
      "",
      "**Fullstack Developer - Autônomo (02/2021 – 11/2021)**",
      "- Desenvolvimento de componentes e páginas responsivas",
      "- Frontend: React.js e TypeScript",
      "- Backend: Node.js e Express",
      "- Implementação de arquiteturas limpas",
    ],
  },
  {
    title: "Educação:",
    text: [
      "**AI Literacy**",
      "- Instituição: Triggo.AI",
      "- Competências: Treinamento sobre IAs e seu uso prático",
      "",
      "**AWS Lambda & Serverless - Developer Guide with Hands-on Lab**",
      "- Instituição: Udemy",
      "- Competências: Amazon Cognito, API Gateway, Amazon DynamoDB, AWS Lambda, Amazon S3, Amazon SQS",
      "",
      "**Curso de Java**",
      "- Instituição: Rocketseat",
      "- Competências: Spring Boot, Java",
      "",
      "**Docker para Desenvolvedores (com Docker Swarm e Kubernetes)**",
      "- Instituição: Udemy",
      "- Competências: Docker, Docker Swarm, Kubernetes",
      "",
      "**TypeScript do Básico ao Avançado (c/ React, Express)**",
      "- Instituição: Udemy",
      "- Competências: Git, Node.js, React.js, Yarn, Desenvolvimento Full Stack, TypeScript, JavaScript",
      "",
      "**Node.js Microservices: NestJS, RabbitMQ and Cloud Services**",
      "- Instituição: Udemy",
      "- Competências: Git, Node.js, React.js, CSS, Yarn, NestJS, Desenvolvimento Full Stack, TypeScript, JavaScript, MongoDB",
      "",
      "**Curso Web Moderno Completo com JavaScript + Projetos**",
      "- Instituição: Udemy",
      "- Competências: SASS, Git, Node.js, React.js, CSS, Yarn, Desenvolvimento Full Stack, Express.js, JavaScript, MongoDB",
    ],
  },
];
